version: "3.8"

services:
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: etl_user
      POSTGRES_PASSWORD: etl_pass
      POSTGRES_DB: etl_demo
    ports:
      - "5433:5432"   # host 5433 -> container 5432 (so host tools don't clash)
    volumes:
      - pg_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:3.1.0
    user: "root"
    depends_on:
      - postgres
      - minio
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://etl_user:etl_pass@postgres:5432/etl_demo
      AIRFLOW__CORE__FERNET_KEY: NkGTyoqalHRBQKcDF_3zcL7dHi2X8s_hqVdybgV1ksU=
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    ports:
      - "8080:8080"
    command: >
      bash -c "
      pip install --user -r /opt/airflow/mini-etl/requirements.txt &&
      airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com --force || true &&
      airflow standalone"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./:/opt/airflow/mini-etl
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 30s
      retries: 5


volumes:
  minio_data:
  pg_data:
